### ISSUE TITLE
Same config except gpu

### ISSUE THREAD

**Issue by dikeckaan** [QuantumShqipe/Opencore-0.6.6-Msi-B450-Tomahawk-Max-Ryzen-9-3900x#1]
Hello , i use your config with msi mech rx 5500 xt 4G (pikera mode  already added), tried 11.0.1 and 11.1 but every time stuck at black screen and i press all keyboard keys 5 min then it booted login screen. How can i fix that?

I like your work , thank you for all.

**Comment by dikeckaan** [comment]
Geekbench scores

Hackintosh with your efi :

https://browser.geekbench.com/v5/cpu/6232240
https://browser.geekbench.com/v5/compute/2334943

Windows :

https://browser.geekbench.com/v5/cpu/6232431
https://browser.geekbench.com/v5/compute/2335014


I love the performance of hackintosh , thanks a lot :) i've only one bug which i mention before.

**Comment by dikeckaan** [comment]
I found true bios settings and tested with big sur 11.2 it works like helll 👍🏻  just need disable in  biost > ctrl-f > serial port > disabled. Tomorrow I can made new branch for gpu of 5500 xt if you want apply

**Comment by ColdIllyrian** [comment]
Hey man so sorry I haven’t seen these messages so glad you like my work , I am now using a MacPro7,1 and will make changes for the opencore 0.6.6 this will enable full hardware acceleration and hopefully further improve your geekbench scores :)

**Comment by dikeckaan** [comment]
Very nice :) I see u r curtana dev  too :)

**Comment by ColdIllyrian** [comment]
yes I am - also for Andromeda haha
