### ISSUE TITLE
config.plist corrupted

### ISSUE THREAD

**Issue by nickxab** [QuantumShqipe/Opencore-0.6.6-Msi-B450-Tomahawk-Max-Ryzen-9-3900x#2]
Hello ! 
Thanks for this package. 😄 
Altho config.plist seems corrupted. 
OpenCore Sanity Checker gives these errors:
`
    Opening and ending tag mismatch: dict line 2143 and array line 2167
    Opening and ending tag mismatch: plist line 3 and dict line 2189
    Extra content at the end of the document line 2190
    Your config.plist contains invalid XML and will not parse
`

And also ProperTree app gives this error
`missmatched tag: line 2167, column 5`

**Comment by ColdIllyrian** [comment]
Lol one sec lemme just fix this dumbass error

**Comment by ColdIllyrian** [comment]
How's that now all good?
