### ISSUE TITLE
Hackintosh  version

### ISSUE THREAD

**Issue by shaojs321** [QuantumShqipe/Opencore-0.6.6-Msi-B450-Tomahawk-Max-Ryzen-9-3900x#3]
Fortunately, the configuration CPU and main board of my computer are the same as yours, which means I can use your EFI for reference. However, I am not familiar with Hackintosh, so I would like to know which Hackintosh system this EFI belongs to, thank you

**Comment by ColdIllyrian** [comment]
Belongs to the MacPro 7,1 you need to setup a custom memory map to avoid any issue with pop-ups as the kext won't work on bigsur.
